#!/bin/bash

echo "🚀 GUÍA RÁPIDA PARA PUBLICAR DEVINT.CL"
echo "====================================="
echo ""
echo "PASO 1: Crear repositorio en GitHub"
echo "   • Ve a: https://github.com/new"
echo "   • Nombre sugerido: devint-website"
echo "   • Descripción: Sitio corporativo de Devint (Astro + Tailwind)"
echo "   • Configura como público y sin archivos iniciales"
echo ""
echo "PASO 2: Conectar el repo local"
echo "   git remote remove origin 2>/dev/null || true"
echo "   git remote add origin https://github.com/TU-USUARIO/devint-website.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "PASO 3: Desplegar en Vercel"
echo "   • Ve a https://vercel.com/new"
echo "   • Importa el repositorio"
echo "   • Selecciona el framework Astro (ya detectado)"
echo "   • Variables recomendadas:"
echo "       VERCEL_URL (se genera automáticamente)"
echo "   • Ejecuta el deploy"
echo ""
echo "📁 ESTRUCTURA DEL PROYECTO"
echo "   • src/content → collections (services, blog)"
echo "   • src/pages → rutas estáticas y dinámicas"
echo "   • src/utils → helpers de SEO, formato y validaciones"
echo ""
echo "✅ Checklist antes de publicar"
echo "   • npm install"
echo "   • npm run check"
echo "   • npm run build"
echo ""
echo "Listo, Devint.cl quedará desplegado con contenido actualizado y formularios validados."
