#!/bin/bash

echo "🚀 GUÍA PARA SUBIR GENERACIÓN URBANA A GITHUB"
echo "=============================================="
echo ""
echo "PASO 1: Crear repositorio en GitHub"
echo "   • Ve a: https://github.com"
echo "   • Haz clic en 'New repository'"
echo "   • Nombre: generacion-urbana-costurera"
echo "   • Descripción: 🧵 Sitio web moderno para costurera experta en San Bernardo"
echo "   • Público: ✅"
echo "   • NO añadas README, .gitignore o license"
echo "   • Haz clic en 'Create repository'"
echo ""
echo "PASO 2: Ejecutar estos comandos EN ORDEN:"
echo "   git remote remove origin 2>/dev/null || true"
echo "   git remote add origin https://github.com/TU-USUARIO/generacion-urbana-costurera.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "PASO 3: Configurar Vercel (opcional)"
echo "   • Ve a: https://vercel.com"
echo "   • Conecta tu repositorio de GitHub"
echo "   • Deploy automático configurado ✅"
echo ""
echo "📁 ESTRUCTURA DEL PROYECTO:"
echo "   • Astro v5.13.7 + Tailwind CSS"
echo "   • Componentes modernos y responsivos"
echo "   • SEO optimizado para 'costurera san bernardo'"
echo "   • Galería de productos con filtros"
echo "   • Secciones de conversión optimizadas"
echo ""
echo "✨ CARACTERÍSTICAS DESTACADAS:"
echo "   • Hero con enfoque en conversión"
echo "   • ServicesHighlight con efectos 3D"
echo "   • ProductGallery con filtros interactivos"
echo "   • Footer moderno con gradientes"
echo "   • Header/Nav optimizado para mobile"
echo ""
echo "🎯 KEYWORDS OBJETIVO:"
echo "   • costurera san bernardo"
echo "   • bordados empresariales"
echo "   • uniformes escolares"
echo "   • polerones cuarto medio"
echo ""
echo "¡Listo para dominar el mercado local de costura! 🧵✨"